### ISSUE TITLE
deepspeech - lm.binary and trie: how to?

### ISSUE THREAD

**Issue by pico977** [MozillaItalia/DeepSpeech-Italian-Model#104]
Dear sir,

I am trying to install a speech recognition system that supports the Italian language for "naomiprojects", and I would like to configure deepspeech as an engine for the STT.
The system asks me for four parameters:
- output_graph.pb
- alphabet.txt
- lm.binary
- trie
But downloading the file recommended by you I find only:
- output_graph.pbmm
- alphabet.txt

Could you help me understand how to proceed?

Thank you and sorry for my english

**Comment by Mte90** [comment]
This stuff is required to usethe DS but you need to download the model, if you check the readme written in italian is is explained how to use the various commands https://github.com/MozillaItalia/DeepSpeech-Italian-Model

**Comment by pico977** [comment]
Benchè sia scritto in italiano non mi è per nulla chiaro cosa devo fare, altrimenti lo avrei già fatto.
Grazie lo stesso per il tempo speso per rispondermi

ciao

**Comment by Mte90** [comment]
Ciao, cosa non ti è chiaro? siamo sempre aperti a suggerimenti.
Ci trovi anche su telegram con @mozitabot nel gruppo developers

**Comment by nefastosaturo** [comment]
> Dear sir,
> 
> I am trying to install a speech recognition system that supports the Italian language for "naomiprojects", and I would like to configure deepspeech as an engine for the STT.
> The system asks me for four parameters:
> 
> * output_graph.pb
> * alphabet.txt
> * lm.binary
> * trie
>   But downloading the file recommended by you I find only:
> * output_graph.pbmm
> * alphabet.txt
> 
> Could you help me understand how to proceed?
> 
> Thank you and sorry for my english

Hello there,

please check your DeepSpeech version because from the 0.8 (or maybe the 0.7 i don't remember) lm.binary and trie files are merged together into a "scorer" file. Also, I think is better to use the output_graph.pbmm file because is the memory-mapped one and thus is smaller.

Consider that this repository is using DeepSpeech 0.8.0 as described in the README https://github.com/MozillaItalia/DeepSpeech-Italian-Model#quick-start
