### ISSUE TITLE
New books from Librivox

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/DeepSpeech-Italian-Model#25]
The idea is to add audio books (not about poetry/prose) written after 1930 from Librivox (are released CC0) and that the author is died since 70 years.
Also recording more then 1 hour.
We can accept books also released before but with a modern italian.

**The big point is we need also an importer for deepspeech** of that like for https://github.com/MozillaItalia/DeepSpeech-Italian-Model/blob/master/DeepSpeech/it/import_m-ailabs.sh.

List (books from D'annunzio. Pascoli, Pirandello, Verga):

* https://librivox.org/il-giornalino-di-gian-burrasca-by-vamba/
* https://librivox.org/il-fu-mattia-pascal-by-luigi-pirandello/
* https://librivox.org/mastro-don-gesualdo-by-giovanni-verga/
* https://librivox.org/i-malavoglia-by-giovanni-verga
* https://librivox.org/le-meraviglie-del-duemila-by-emilio-salgari/
* https://librivox.org/novelle-per-un-anno-vol-2-la-vita-nuda-by-luigi-pirandello/
* https://librivox.org/novelle-per-un-anno-vol-1-scialle-nero-by-luigi-pirandello/
* https://librivox.org/novelle-per-un-anno-vol-6-in-silenzio-by-luigi-pirandello/
* https://librivox.org/vagabondaggio-by-giovanni-verga/

**Comment by simevo** [comment]
For this task I propose the following plan of attack:

1. Perform a systematic search on librivox of Italian language audio-books
2. Manually select of a corpus of suitable audio-books
3. Download, extract ZIPs
4. Find TXT files with the original text for each mp3 file (if necessary manually splitting files etc.)
5. ?

I have done steps 1, 2 and 3.

## Step 1

Yesterday (2020-05-12) I searched the librivox website for Italian audio-books to listen, sorted by “Release date” (this should make it easier to update the list later):
https://librivox.org/search?primary_key=4&search_category=language&search_page=1&search_form=get_results

The search returns “135 books” but actually 157 records are returned; for some reason it does not return “Il fu Mattia Pascal” by Luigi PIRANDELLO, which I manually added.

## Step 2

I have selected a corpus of 33 suitable audio-books, for a total of 103,74 hours and 2960.6 MB in mp3 format.
Note that “Novelle per un anno” by Luigi PIRANDELLO was released multiple times, each time adding a new chapter, so we should only take it once.

I rearranged the list in this LibreOffice spreadsheet:
[librivox_it.zip](https://github.com/MozillaItalia/DeepSpeech-Italian-Model/files/4621581/librivox_it.zip)

The resulting corpus as a single TAR file (2,8 GB) can be downloaded with the bittorrent protocol with this magnet link: `magnet:?xt=urn:btih:1c38695008d73eddca230f96e75c079f516f7502&dn=corpus.tar`.

## Next steps

We should extract the ZIP files and find the corresponding TXT files.
Do we need to split the MP3 files in 5-10 seconds clips ?

**Comment by Mte90** [comment]
I did a manual selection because librivox report badly the release date also including books of XIV century, for copyright reasons and for the kind of italian used. 
So this **dataset that you shared cannot be used for our purpose**. For sure the list of books can extended but an automated way is not the right way.

The second point is about the dataset structure that is not fine for DeepSpeech. We need to do an importer (deepspeech require wav files anyway) as written in the first comment or otherwise do a dataset that is strutucred the same as common voice dataset, csv with all the wav files and the file with the text (there is a package example of cv dataset at https://github.com/MozillaItalia/DeepSpeech-Italian-Model/files/4610711/cv-it_tiny.tar.gz).

I have to remove the magnet link to avoid issues with copyright. I suggest to you to join our telegram groups instead of doing something before discussing with the rest of team to optimize the result :-)

**Comment by simevo** [comment]
Sorry I don't use Telegram.

I did a manual selection too ("_2. Manually select of a corpus of suitable audio-books_"), my contribution is about making it _systematically_ so that we don't miss anything. Can you comment on my manual selection of 33 audio-books in the LibreOffice file ? Is there any file that we can not take for some reason ?

Regarding the import, I noticed that the datasets are usually in the form of short clips (5-10 seconds) and the authoritative text is given separately for each clip.

Splitting can be done using mp3splt; for example `mp3splt -s -p th=-39 human_rights_un_ita_dan.mp3`, gives 142 files with average duration 6.2 seconds (min = 1.21, max = 28.56).

Converting the files to WAV can be done with the command `find . -name 'human_rights_un_ita_dan_silence_*.mp3' | xargs -n 1 ./process.sh`, where process.sh contains:

    #!/bin/sh
    sox "${1%.*}.mp3" "${1%.*}.wav"


The challenging part is splitting the authoritative text for each clip.
Have you done this for other corpuses in the past ?

**Comment by Mte90** [comment]
All the discussion about the development of this project happens on Telegram so if you are interested to contribute I invite to you to join our discussion channels, just because a chat is more simple for some stuff.

Anyway I saw the spreadsheet and as I written in the first comment the rule was just the books with at least 1 hour of recording (to focus on big books but we can add also the tiny ones is no a big problem).

The real problem is that some of this books are before of 1930 (again written in the first comment) as we in the project define as minimum year for the Italian style (it will be better 1940 but there is a lot of stuff under copyright). 

About CV they are tiny sets because voice.mozilla.org is based on single sentence read it, but this project use also M-Ailabs that doesn't work in this manner so this is not a problem.

For the whole project the problem is the copyright and the italian style (juridic, poetic and so on) or year of production when we are talking about datasets.

**Comment by eziolotta** [comment]
Hi, the problem is that the LibriVox dataset is only audio, no audio trascription are supported.
Furthermore, single sample have a medium duration of several minutes.
Unlike M-Ailabs, audio are short and transcribed, useful for train this kind of model, 

In python code in import_m-ailabs.py the transcript is put into generated files for training.

A similar dataset could also be generated with LibriVox, but it is difficult, but possible, according to me..
1) The audios are always faithful to the original lyrics
Example:
For the first link reported by Mte90 https://librivox.org/il-giornalino-di-gian-burrasca-by-vamba/ there are 102 audio files.
The first file of the 102 corresponds exactly to the original text of the work, in this case https://it.wikisource.org/wiki/Il_giornalino_di_Gian_Burrasca/20_settembre)

2) The difficulty is then to obtain audio clips transcribed automatically, here we need an Italian Forced Aligner, I don't know any with Open license

**Comment by Mte90** [comment]
I think that is better to close it as we don't have the resources to manipulate all the audio recordings to fit our needs.
