### ISSUE TITLE
Improve download status for Mitads

### ISSUE THREAD

**Issue by Mte90** [MozillaItalia/DeepSpeech-Italian-Model#84]
This is what happens with `parlareitaliano`:
```
...17066%, 0 MB, 58052 KB/s, 0 seconds passedDownloading in ./parsing/parlareitaliano/b01f001f.hsw
...12047%, 0 MB, 45343 KB/s, 0 seconds passedDownloading in ./parsing/parlareitaliano/b01f003f.hsw
...24824%, 0 MB, 59074 KB/s, 0 seconds passedDownloading in ./parsing/parlareitaliano/b01f005f.hsw
```

We need to test all the importers for their status bar because sometimes don't works flawlessy.

**Comment by ilyasmg** [comment]
in all the scripts?

**Comment by Mte90** [comment]
Yes, we have an internal library but doesn't works often

**Comment by ilyasmg** [comment]
I don't think that problem is due to the progress bar itself. I tried with a different progress bar implementation and I get the same result: for corpus_api.py the progress starts at 100% and the seconds count do not start. This problem happens only with corpus_api.py and not with the other scrapers

**Comment by Mte90** [comment]
So it is a bug just of that corpus.
This https://github.com/MozillaItalia/DeepSpeech-Italian-Model/pull/103 fix the issue?

**Comment by ilyasmg** [comment]
No, it doesn't. Now the % won't go over 100% and I added a line break

**Comment by Mte90** [comment]
Well anyway is a bugfix :-D
